name: digitalbharat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.7+3
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  permission_handler: ^10.2.0
  sqflite: ^2.3.0
  path: ^1.8.3


  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: 

flutter:
  assets:
    - assets/mit_logo.png
    - assets/student.jpg
    - assets/event_placeholder.jpg
  uses-material-design: true

